### ISSUE TITLE
White screen when querying multiple studies

### ISSUE THREAD

**Issue by kcourtet** [thehyve/cbioportal-docker#45]
Hi ! I can't submit a query by selecting more than one study, or it returns an empty page. But there is no problem if I select only one study, the Oncoprint view is displayed normally. Is there anybody who can help me to find any explanation to this ?

Regards

**Comment by Sjoerd-van-Hagen** [comment]
Hi!
This is probably caused  a known issue with the so called session service. The session service is optional in cBioPortal installations and not part of the Docker setup. This was not a problem before but due to some changes made in the refactoring this has become one. At The Hyve we are planning to update the Docker image with the session service. At the same time MSK is working to make it optional again. Hopefully we can release an updated docker image soon.
Best,
Sjoerd.

**Comment by kcourtet** [comment]
I just re-installed the docker image with the latest version (1.17.1 ) and all have been resolved. 
Thank !
